apiVersion: v1
kind: Pod
metadata:
  labels:
    run: centos-pod-chown-privileged
  name: centos-pod-chown-privileged
spec:
  containers:
  - image: centos
    name: centos
    stdin: true
    tty: true
    securityContext:
      capabilities:
        drop:
        - CHOWN