apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kuard-rs-test
spec:
  maxReplicas: 20
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: ReplicaSet
    name: kuard-rs-test
  targetCPUUtilizationPercentage: 50
