apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      volume: db-pv